### ISSUE TITLE
Make it possible to also use save_weights() instead of save()

### ISSUE THREAD

**Issue by stk-code** [dorukkarinca/keras-buoy#3]
Using model.save and the h5 extension, results in an arror for subclass based models.

```
NotImplementedError: Saving the model to HDF5 format requires the model to be a Functional model or a Sequential model. It does not work for subclassed models, because such models are defined via the body of a Python method, which isn't
safely serializable. Consider saving to the Tensorflow SavedModel format (by setting save_format="tf") or using `save_weights`.
```

Could you offer an alternative option to use `model.save_weights()` ?

**Comment by dorukkarinca** [comment]
Thanks for noticing this. Based on [Tensorflow docs](https://www.tensorflow.org/guide/keras/save_and_serialize) it seems that letting users save the model with a non-h5 extension will save it in the new SavedModel format automatically. I am backed up right now but feel free to submit a PR that allows any file extension (or no extension). Otherwise I'll get back to it soon.

**Comment by dorukkarinca** [comment]
Curious: does it solve your problem if you remove [this line](https://github.com/dorukkarinca/keras-buoy/blob/master/src/keras_buoy/models.py#L29) and use a different extension?

**Comment by dorukkarinca** [comment]
[This commit](https://github.com/dorukkarinca/keras-buoy/commit/00ddfbc5e467dd602f0900012ae3f16bee2c72e7) should address this issue. Uploading version 0.1.4 to pip in a bit. If the error persists, we can reopen.
